---
- name: Manage postfix installation
  hosts: stmail01
  become: true
  # gather_facts: false
  vars:
    stuser: kirsty
    stpassword: ksH85UJjhb
    stmaildomain: stratos.xfusioncorp.com
    stmailhost: stmail01
  tasks:

  - name: create/update user mail user
    ansible.builtin.user:
      name: "{{ stuser }}"
      password: "{{ stpassword | password_hash('sha512') }}"

  - name: install package postfix
    ansible.builtin.package:
      name: postfix
      state: present

  - name: prepare data
    ansible.builtin.set_fact:
      pfix:
        - name: myhostname
          value: "{{ stmailhost }}.{{ stmaildomain }}"
        - name: mydomain
          value: "{{ stmaildomain }}"
        - name: myorigin
          value: "$mydomain"
        - name: inet_interfaces
          value: all
        - name: mydestination
          value: "$myhostname, localhost.$mydomain, localhost, $mydomain"
        - name: mynetworks
          value: "172.16.238.0/24, 127.0.0.0/8"
        - name: home_mailbox
          value: "Maildir/"

  - name: mask current settings in postfix/main.cf
    ansible.builtin.lineinfile:
      path: /etc/postfix/main.cf
      regexp: '^{{ item.name }}(.*)$'
      line: '#{{ item.name }}\1'
      backrefs: yes
    loop: '{{ pfix }}'

  - name: add postfix/main.cf lines 
    ansible.builtin.lineinfile:
      path: /etc/postfix/main.cf
      insertafter: '^#{{ item.name }}.*'
      line: '{{ item.name }} = {{ item.value }}'
    loop: '{{ pfix }}'

  - name: restart service postfix
    ansible.builtin.service:
      name: postfix
      state: restarted
