---
- name: Manage postfix installation
  hosts: localhost
  become: true
  # gather_facts: false
  vars:
    stuser: john
    stpassword: 123123
    stmaildomain: stratos.xfusioncorp.com
    stmailhost: stmail01
  tasks:

  - name: create/update user mail user
    ansible.builtin.user:
      name: "{ stuser }"
      password: "{{ stpassword | password_hash('sha512') }}"

  - name: install package postfix
    ansible.builtin.package:
      name: postfix
      state: started

  - name: prepare data
    ansible.builtin.set_fact:
      pfix:
        - name: myhostname
          value: "{{ stmailhost }}.{{ stmaildomain }}"
        - name: mydomain
          value: "{{ stmaildomain }}"
        - name: myorigin
          value: $mydomain
        - name: inet_interfaces
          value: all
        - name: mydestination
          value: $myhostname, localhost.$mydomain, localhost, $mydomain
        - name: mynetworks
          value: 172.16.238.0/24, 127.0.0.0/8
        - name: home_mailbox
          value: Maildir/

  # - name: prepare file
  #   ansible.builtin.copy:
  #     src: main.cf.original
  #     dest: main.cf

  - name: add postfix/main.cf lines 
    ansible.builtin.lineinfile:
      path: /etc/postfix/main.cf
      regexp: '^#{{ item.name }}.*'
      line: '{{ item.name }} = {{ item.value }}'
    loop: '{{ pfix }}'

  - name: make postfix/main.cf lines unique
    ansible.builtin.lineinfile:
      path: /etc/postfix/main.cf
      regexp: '^{{ item.name }} = (?!{{ item.value }})'
      state: absent
    loop: '{{ pfix }}'

