---
- name: create thor user at all hosts
  hosts: all
  become: yes
  tasks:
  - name: create/update user thor
    user:
      name: thor
      password: "{{ '111' | password_hash('sha512') }}"
      append: True
      groups: wheel
  - name: ssh config without fingertips
    blockinfile:
      path: /home/thor/.ssh/config
      block: |
        Host *
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null

  #- name: ssh config without fingertips
  #  file:
  #    path: /home/thor/.ssh
  #    state: directory
  #    owner: thor
  #    group: thor
  #- name:
  #  copy:
  #    src: .ssh/config
  #    dest: /home/thor/.ssh/config
