---
- name: create thor user at all hosts
  hosts: all
  become: yes
  tasks:
  - name: create/update user thor
    user:
      name: thor
      password: "{{ '111' | password_hash('sha512') }}"
      append: True
      groups: wheel
  - name: ssh config without fingertips
    blockinfile:
      path: /home/thor/.ssh/config
      create: True
      block: |
        Host *
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
