---
- name: create keys
  hosts: localhost
  tasks:
  - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
    community.crypto.openssh_keypair:
      path: /tmp/id_rsa
      delegate_to: localhost

---
- name: create thor user at all hosts
  hosts: all
  become: yes
  tasks:

  - name: create/update user thor
    ansible.builtin.user:
      name: thor
      password: "{{ '1' | password_hash('sha512') }}"
      home: /home/thor
      append: True
      groups: wheel

  - name: Directory attributes
    ansible.builtin.file:
      path: /home/thor/.ssh
      state: directory
      recurse: yes
      mode: 0700
      owner: thor
      group: thor
      
  - name: ssh config without fingertips
    ansible.builtin.blockinfile:
      path: /home/thor/.ssh/config
      owner: thor
      group: thor
      mode: 0600
      create: True
      block: |
        Host *
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null

  - name: create ssh private key
    ansible.builtin.copy:
      dest: /home/thor/.ssh/id_rsa
      src: /tmp/id_rsa
      owner: thor
      group: thor
      mode: 0600

  - name: create ssh public key
    ansible.builtin.copy:
      dest: /home/thor/.ssh/id_rsa.pub
      src: /tmp/id_rsa.pub
      owner: thor
      group: thor
      mode: 0600

  - name: create authorized_keys
    ansible.builtin.copy:
      dest: /home/thor/.ssh/authorized_keys
      src: /tmp/id_rsa.pub
      owner: thor
      group: thor
      mode: 0600
