---
- name: create thor user at all hosts
  hosts: all
  become: yes
  tasks:
  - name: create/update user thor
    user:
      name: thor
      password: "{{ '111' | password_hash('sha512') }}"
      append: True
      groups: wheel
  - name: ssh config without fingertips
    copy:
      src: .ssh
      dest: /home/thor/.ssh
